#!/usr/bin/with-contenv bash

# Copy over modified nginx.conf
if [ ! -f /config/nginx/.nginx.conf.original ]; then
  echo '--------------------------------------'
  echo '|      Backing up Nginx config       |'
  echo '--------------------------------------'
  mv /config/nginx/nginx.conf /config/nginx/.nginx.conf.original
  echo '--------------------------------------'
  echo '|     Copying Nginx config file      |'
  echo '--------------------------------------'
  cp /defaults/nginx.conf /config/nginx/nginx.conf
fi

# Backup the www.conf file for PHP-FPM if it exists & copy in www.conf for PHP-FPM
if [ ! -f /etc/php7/php-fpm.d/www.conf.original ]; then
  echo '--------------------------------------'
  echo '|      Backing up www.conf file      |'
  echo '--------------------------------------'
  mv /etc/php7/php-fpm.d/www.conf /etc/php7/php-fpm.d/www.conf.original
  echo '--------------------------------------'
  echo '|       Copying www.conf file        |'
  echo '--------------------------------------'
  cp /defaults/www.conf /etc/php7/php-fpm.d/www.conf
elif [[ ! -f /config/php/www.conf ]]; then
  cp /defaults/www.conf /etc/php7/php-fpm.d/www.conf
fi

# Copy over php.conf
if [ ! -f /config/nginx/.php.conf.original ]; then
  echo '--------------------------------------'
  echo '|      Copying PHP config file       |'
  echo '--------------------------------------'
  cp /defaults/php.conf /config/nginx/php.conf
fi

# Copy over modified default site file to use PHP-FPM
if [ ! -f /config/nginx/site-confs/.default.original ]; then
  echo '--------------------------------------'
  echo '|     Copying default site file      |'
  echo '--------------------------------------'
  cp /defaults/default /config/nginx/site-confs/default
fi

# Check for the include for the healthcheck conf and, if it does not exist, add it
if [[ $(grep -c healthcheck /config/nginx/site-confs/default) -eq 0 ]]; then
  echo '--------------------------------------'
  echo '|  Updating default for healthcheck  |'
  echo '--------------------------------------'
  sed -i $'s|root /config/www/plpp;|root /config/www/plpp;\\\n  include /config/nginx/healthcheck.conf;|g' /config/nginx/site-confs/default
elif [[ $(grep -c healthcheck /config/nginx/site-confs/default) -ge 1 ]]; then
  :
fi

# Check for the try_files line for CVE-2019-11043 and, if it does not exist, add it
if [[ $(grep -c try_files /config/nginx/php.conf) -eq 2 ]]; then
  sed -i $'s|fastcgi_split_path_info \^(\.+\\\.php)(\/\.+)\$;|fastcgi_split_path_info \^(\.+\\\.php)(\/\.+)\$;\\\n          try_files $fastcgi_script_name =404;|g' /config/nginx/php.conf
elif [[ $(grep -c try_files /config/nginx/php.conf) -ge 3 ]]; then
  :
fi

# Check for the fastcgi_hide_header line and, if it does not exist, add it
if [[ $(grep -c fastcgi_hide_header /config/nginx/php.conf) -eq 0 ]]; then
  sed -i $'s|include /etc/nginx/fastcgi_params;|include /etc/nginx/fastcgi_params;\\\n          fastcgi_hide_header X-Powered-By;|g' /config/nginx/php.conf
elif [[ $(grep -c fastcgi_hide_header /config/nginx/php.conf) -ge 1 ]]; then
  :
fi

# Copy over Nginx status config file if it doesn't exist
if [ ! -f /config/nginx/healthcheck.conf ]; then
  echo '--------------------------------------'
  echo '|   Copying Nginx status conf file   |'
  echo '--------------------------------------'
  cp /defaults/healthcheck.conf /config/nginx/healthcheck.conf
else
  :
fi

# Triple-checking permissions are correct
chown -R abc:abc \
  /config
