#!/usr/bin/with-contenv bash

# Copy over modified default site file
# to use PHP-FPM
if [ ! -f /config/nginx/site-confs/.default.original ]; then
  echo '--------------------------------------'
  echo '|      Backing up default file       |'
  echo '--------------------------------------'
  mv /config/nginx/site-confs/default /config/nginx/site-confs/.default.original
  echo '--------------------------------------'
  echo '|      Copying default site file     |'
  echo '--------------------------------------'
  cp /defaults/default /config/nginx/site-confs/default
fi

# Triple-checking permissions are correct
# Set Permissions
chown -R abc:abc \
  /config
